# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  linters:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip six
          pip install -r backend/src/requirements.test

      - name: Run isort
        run: |
          isort ./backend/src -c

#      - name: Run flake8
#        run: |
#          python -m flake8 backend/src --config=backend/.flake8
#
#      - name: Run pylint
#        run: |
#          python -m pylint backend/src --rcfile=backend/pylintrc